### ISSUE TITLE
Auto-scrolls down when static content fits in screen

### ISSUE THREAD

**Issue by acrespofn** [ngocchung/NestedScrollView#2]
When putting "static" (CardViews, LinearLayouts, etc...) above the RecyclerView, and this content/layouts fit into the screen (they do not need scrolling down), when loading the activity/fragment, it "scrolls down"  to the start of the RecyclerView (Leaving the top of the recyclerview at the top of the screen, just below the toolbar).

To see this behaviour just comment out or remove one of the CardViews at `content_main.xml`.

**Comment by ngocchung** [comment]
@acrespofn  thanks for your comment. For your issue, please add android:descendantFocusability="blocksDescendants" in the first RelativeLayout under the NestedScrollView. I have just updated `content_main.xml` too

**Comment by ngocchung** [comment]
@acrespofn have you tried it yet? If it works, this issue should be closed :)

**Comment by acrespofn** [comment]
Thanks @ngocchung! Worked like a charm! Closing!
