### ISSUE TITLE
Does RV recycle views by this approach?!

### ISSUE THREAD

**Issue by IRMobydick** [ngocchung/NestedScrollView#4]
I'm using recyclerview inside NestedScrollView as same as you done! but [check this out](http://stackoverflow.com/questions/37590651/recyclerview-does-not-recycling-views-when-use-it-inside-nestedscrollview)

**Comment by ngocchung** [comment]
@IRMobydick Hi! Sorry I have no working solution for that issue at present

**Comment by IRMobydick** [comment]
Okay! Then I close it ;)
